spring:
  datasource:
    # url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:wyzecmsdb}
    # username: ${DB_USER_NAME:dev}
    # password: ${DB_PASSWORD:dev@c00l!}
    # driver-class-name: org.postgresql.Driver
    
     url: jdbc:mysql://${DB_HOSTNAME:localhost}:${DB_PORT:3306}/${DB_NAME:wyzecmsdb}
     username: ${DB_USER_NAME:dev}
     password: ${DB_PASSWORD:dev@c00l!}
     # driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    # database-platform: org.hibernate.dialect.MariaDBDialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    # database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    show-summary-output: all
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
      
debug: true
          
xabisa:
  security:
    secret:${xabisa.env.security.SECRET:S3crEtn0t54f33hBf&g9jHg4Y6bgDre36vcX7}
    expiration:${xabisa.env.security.EXPIRATION:604800}
    
logging:
  charset:
    console: UTF-8
  level:
    root: warn
    za.co.wyzetech: trace
